// Fetches brand glyph paths from Simple Icons and bakes them into
// lib/icons.generated.ts so the app has zero runtime dependency and works
// offline. Re-run when you add a new icon slug: `node scripts/fetch-icons.mjs`.
import { writeFileSync } from "node:fs";

const slugs = [
  // existing
  "typescript",
  "react",
  "nextdotjs",
  "zod",
  "tailwindcss",
  "radixui",
  "hono",
  "expo",
  "vercel",
  "supabase",
  "datocms",
  "cloudflareworkers",
  "pnpm",
  "playwright",
  "vitest",
  "claude",
  // enrichment from repo scan
  "reacthookform",
  "graphql",
  "framer",
  "reactquery",
  "laravel",
  "trpc",
  "reactrouter",
  "greensock",
  "php",
  "shopify",
  "githubactions",
  "algolia",
  "upstash",
  "meilisearch",
  "docker",
  "shadcnui",
  "lucide",
  "turborepo",
  "prisma",
  "storybook",
  "jest",
  "webpack",
];

const out = {};
for (const s of slugs) {
  const url = `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${s}.svg`;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      console.warn(`MISS  ${s} (${res.status})`);
      continue;
    }
    const svg = await res.text();
    const m = svg.match(/<path\s+d="([^"]+)"/);
    if (!m) {
      console.warn(`NOPATH ${s}`);
      continue;
    }
    out[s] = m[1];
    console.log(`OK    ${s}`);
  } catch (err) {
    console.warn(`ERR   ${s}: ${err.message}`);
  }
}

const body = `// AUTO-GENERATED by scripts/fetch-icons.mjs — do not edit by hand.
// Brand glyph paths from Simple Icons (24x24 viewBox, single monochrome path).
export const ICON_PATHS: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(new URL("../lib/icons.generated.ts", import.meta.url), body);
console.log(`\nWrote ${Object.keys(out).length} icons to lib/icons.generated.ts`);
